"project_identifier_env": CROWDIN_PROJECT_IDENTIFIER
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/youtrack-issue-distribution-report-widget.pot",
  "dest": "/widgets/youtrack-issue-distribution-report-widget/youtrack-issue-distribution-report-widget.pot",
  "translation" : "/src/app/translations/youtrack-issue-distribution-report-widget_%two_letters_code%.po",
 }
]
